(function(z){function r(n){var i=r.modules[n];i||console.log("couldn't find module for: "+n);if(!i.exports){i.exports={};i.call(i.exports,i.exports,A(n))}return i.exports}function A(n){var i=n.replace(/[^\/]*$/,"");return function(f){f=(i+f).replace(/\/\.\//,"/").replace(/[^/]*\/\.\./,"").replace(/\/\//,"/");return r(f)}}r.modules={};r.module=function(n,i){r.modules["./"+n]=i};r.module("base64",function(n){var i={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_=",encode_safe:function(f){var g=
"",a,c,b,m,o,l,d=0;for(f=i._utf8_encode(f);d<f.length;){a=f.charCodeAt(d++);c=f.charCodeAt(d++);b=f.charCodeAt(d++);m=a>>2;a=(a&3)<<4|c>>4;o=(c&15)<<2|b>>6;l=b&63;if(isNaN(c))o=l=64;else if(isNaN(b))l=64;g=g+i._keyStr.charAt(m)+i._keyStr.charAt(a)+i._keyStr.charAt(o)+i._keyStr.charAt(l)}return g},decode_safe:function(f){var g="",a,c,b,m,o,l=0;for(f=f.replace(/[^A-Za-z0-9\-\_\=]/g,"");l<f.length;){a=i._keyStr.indexOf(f.charAt(l++));c=i._keyStr.indexOf(f.charAt(l++));m=i._keyStr.indexOf(f.charAt(l++));
o=i._keyStr.indexOf(f.charAt(l++));a=a<<2|c>>4;c=(c&15)<<4|m>>2;b=(m&3)<<6|o;g+=String.fromCharCode(a);if(m!=64)g+=String.fromCharCode(c);if(o!=64)g+=String.fromCharCode(b)}return g=i._utf8_decode(g)},_utf8_encode:function(f){f=f.replace(/\r\n/g,"\n");for(var g="",a=0;a<f.length;a++){var c=f.charCodeAt(a);if(c<128)g+=String.fromCharCode(c);else{if(c>127&&c<2048)g+=String.fromCharCode(c>>6|192);else{g+=String.fromCharCode(c>>12|224);g+=String.fromCharCode(c>>6&63|128)}g+=String.fromCharCode(c&63|128)}}return g},
_utf8_decode:function(f){for(var g="",a=0,c=c1=c2=0;a<f.length;){c=f.charCodeAt(a);if(c<128){g+=String.fromCharCode(c);a++}else if(c>191&&c<224){c2=f.charCodeAt(a+1);g+=String.fromCharCode((c&31)<<6|c2&63);a+=2}else{c2=f.charCodeAt(a+1);c3=f.charCodeAt(a+2);g+=String.fromCharCode((c&15)<<12|(c2&63)<<6|c3&63);a+=3}}return g}};n.base64=i});r.module("casti_ctrl_t",function(n,i){var f=i("./neoip_rpc_node");i("sys");var g=i("../vendor/underscore/underscore")._;g.noConflict();var a=function(c){var b=c.call_url||
console.assert(false),m=c.casti_opts||console.assert(false),o=c.event_cb||function(){},l=c.req_timer_delay||500,d=c.verbose||0,h=null,e=null,j=function(){e!==null&&clearTimeout(e);e=null},k=function(){d>1&&console.log("req_timer expired. next in "+l+"-msec");q()},p=null,q=function(){d>1&&console.log("rpc: rpc_call_request enter");console.assert(p===null);p=f.rpc_call.create({call_url:b,method_name:"request_stream",method_args:[m.mdata_srv_uri,m.cast_name,m.cast_privtext,m.scasti_uri,m.scasti_mod,
m.http_peersrc_uri,m.web2srv_str],success_cb:function(u){w();j();var y=void 0;if(y==undefined)y=l;console.assert(e===null);e=setTimeout(k,y);if(u.length>0){h=u;s("ispublished",{cast_privhash:u})}else{h=null;s("nopublished",null)}},failure_cb:function(u){h=null;d&&console.log("failure: "+i("sys").inspect(u));w();s("rpc_error",null)}})},t=function(){d>1&&console.log("rpc: rpc_call_release enter");console.assert(p===null);h=null;p=f.rpc_call.create({call_url:b,method_name:"release_stream",method_args:[m.mdata_srv_uri,
m.cast_name,m.cast_privtext],success_cb:function(){w();s("released",null)},failure_cb:function(u){d&&console.log("failure: "+i("sys").inspect(u));w();s("rpc_error",null)}})},w=function(){p!==null&&p.destroy();p=null},x=null,v=null,s=function(u,y){if(!(u==x&&g.isEqual(y,v))){v=y;x=u;o(u,y)}};q();return{release:function(){w();j();t()},published:function(){return h!==null},cast_privhash:function(){return h},destroy:function(){w();j()}}};a.create=function(c){return new a(c)};n.create=a.create});r.module("casto_testclient_t",
function(n,i){var f=i("http"),g=function(a){console.assert(a.stream_url);var c=a.stream_url,b=a.event_cb||function(){},m=a.notify_unit||1024,o=a.verbose||0,l=a.idle_timer_delay||2E4,d=a.max_recved_len||null,h=null,e=function(){o>1&&console.log("launch idle_timer timeout in "+l+"-msec");h=setTimeout(k,l)},j=function(){h!==null&&clearTimeout(h);h=null},k=function(){o&&console.log("idle timer expired. next in "+l+"-msec");b("error","idle timeout after "+l+"-msec")},p=null;(function(){var q=0,t=0,w=i("url").parse(c),
x=f.createClient(w.port||80,w.hostname);x.on("error",function(v){b("error",v.message)});x.on("timeout",function(v){b("error",v.message)});p=x.request("GET",w.pathname,{host:w.host});p.on("response",function(v){o&&console.log("Connected to "+c);e();if(v.statusCode!=200)b("error","statusCode="+v.statusCode);else{b("cnx_begin",null);v.on("data",function(s){o&&console.log("idle_time_refresh");j();e();q+=s.length;s=Math.floor(t/m);s=Math.floor(q/m)-s;s>0&&b("recved_size",s);t=q;d&&q>=d&&b("recved_len_maxed",
null)});v.on("end",function(){o&&console.log("Connection ended");b("cnx_closed",null)})}});p.end()})();return{destroy:function(){j();p.connection.destroy()}}};g.create=function(a){return new g(a)};n.create=g.create});r.module("collection",function(n){n.collection=function(){var i={},f=function(c,b){for(var m=c.split("/"),o=i,l=m[0],d=0;d<m.length-1;d++){typeof o[l]=="undefined"&&b(o,l);o=o[l];l=m[d+1]}return{submap:o,subkey:l}},g=function(c){console.assert(a(c));var b=f(c,function(m,o){throw Error("subkey "+
o+" (from key "+c+") doesnt exist");});return b.submap[b.subkey]},a=function(c){var b=null;try{b=f(c,function(o,l){throw Error("subkey "+l+" (from key "+c+") doesnt exist");})}catch(m){return false}if(typeof b.submap[b.subkey]=="undefined")return false;return true};return{set:function(c,b){var m=f(c,function(o,l){o[l]={}});m.submap[m.subkey]=b},get:g,get_dfl:function(c,b){return a(c)?g(c):b},del:function(c){console.assert(a(c));var b=f(c,function(m,o){throw Error("subkey "+o+" (from key "+c+") doesnt exist");
});delete b.submap[b.subkey]},has:a}}});r.module("neoip_app_detect",function(n,i){var f=typeof process=="object"?i("./neoip_rpc_node").rpc_call:i("./neoip_rpc_web").rpc_call,g={oload:{port_beg:4550,port_end:4553},casto:{port_beg:4560,port_end:4563},casti:{port_beg:4570,port_end:4573}},a={},c=function(e){return e in a},b=function(){a={}},m=function(e,j,k){console.assert(j);console.assert(e=="oload"||e=="casti"||e=="casto");k||(k=function(){});if(e in a){var p=a[e];p.version===false?setTimeout(function(){k(true)},
0):setTimeout(function(){j(p.root_url,p.version)},0)}else{var q=g[e].port_end,t=g[e].port_beg,w=function(s){var u="http://127.0.0.1:"+t;a[e]={root_url:u,version:s};j(u,s)},x=function(){if(t==q){a[e]={version:false};k("not found")}else{t++;v()}},v=function(){f.create({call_url:"http://127.0.0.1:"+t+"/neoip_"+e+"_appdetect_jsrest.js",method_name:"probe_apps",method_args:[],success_cb:w,failure_cb:x})};v()}},o=function(e,j){var k=e.match(/(\d+).(\d+).(\d+)/),p=j.match(/(\d+).(\d+).(\d+)/),q=parseInt(k[1],
10),t=parseInt(p[1],10);if(q>t)return+1;if(q<t)return-1;q=parseInt(k[2],10);t=parseInt(p[2],10);if(q>t)return+1;if(q<t)return-1;k=parseInt(k[3],10);p=parseInt(p[3],10);if(k>p)return+1;if(k<p)return-1;return 0},l={oload:"0.0.1",casto:"0.0.1",casti:"0.0.2"},d=function(){for(var e in l)if(!(e in a))return null;for(e in l)if(a[e].version===false)return"toinstall";for(e in l)if(o(a[e].version,l[e])<0)return"toupgrade";return"installed"},h=function(e){var j=function(){var p=d();p!=null&&e(p)};for(var k in l)m(k,
j,j)};n.discover_app=m;n.discover_webpack=h;n.cache_contain=c;n.cache_get=function(e){return a[e]};n.cache_clear=b;n.avail=function(e){if(!c(e))return false;if(a[e].version==false)return false;return true};n.probe=m;n.webpack_probe=h;n.webpack_avail=function(){return d=="installed"};n.webpack_status=d;n.clear=b});r.module("neoip_jsonp_call",function(n){var i=0;n.jsonp_call=function(f){var g=f.url||console.assert(f.url),a=f.success_cb||function(){},c=f.failure_cb||function(){},b="jsonp_call_cb_"+i++;
console.assert(/callback=\?(&|$)/.test(g));g=g.replace("callback=?","callback="+b);var m=document.getElementsByTagName("head")[0],o=document.createElement("script"),l=function(){m.removeChild(o);window[b]=undefined;try{delete window[b]}catch(d){}};window[b]=function(d){l();a(d)};o.src=g;o.onerror=function(){l();c("Network error")};m.appendChild(o);return{destroy:l}}});r.module("neoip_rpc_node",function(n,i){var f=i("http"),g=function(a){var c=a.call_url||console.assert(a.call_url),b=a.method_name||
console.assert(a.method_name),m=a.method_args||[],o=a.success_cb||function(){},l=a.failure_cb||function(){},d=a.verbose||0,h=null;(function(){for(var e=i("url").parse(c),j=e.pathname+"?method_name="+b,k=0;k<m.length;k++)j+="&arg"+k+"="+escape(m[k]);k=f.createClient(e.port||80,e.hostname);k.on("error",function(p){l({code:-1,string:p.message})});k.on("timeout",function(p){l({code:-1,string:p.message})});h=k.request("GET",j,{host:e.host});h.on("response",function(p){d&&console.log("STATUS: "+p.statusCode);
d&&console.log("HEADERS: "+JSON.stringify(p.headers));if(p.statusCode!=200)return l(Error("http statuscode="+p.statuscode));p.setEncoding("utf8");p.on("data",function(q){d&&console.log("BODY: "+q);q=JSON.parse(q);if(q.fault){d>1&&console.dir(q);l(q.fault)}else o(q.returned_val)})});h.end()})();return{destroy:function(){h.connection.destroy()}}};g.create=function(a){return new g(a)};n.rpc_call=g});r.module("neoip_rpc_web",function(n,i){var f=i("neoip_jsonp_call").jsonp_call,g=function(a){var c=a.call_url||
console.assert(a.call_url),b=a.method_name||console.assert(a.method_name),m=a.method_args||[],o=a.success_cb||function(){},l=a.failure_cb||function(){},d=a.verbose||0,h=null;(function(){console.assert(h==null);for(var e=c+"?callback=?&method_name="+b,j=0;j<m.length;j++)e+="&arg"+j+"="+escape(m[j]);d>1&&console.log("url="+e);h=new f({url:e,success_cb:function(k){d>1&&console.dir(k);k.fault?l(k.fault):o(k.returned_val)},failure_cb:function(k){d&&console.log("failed due to "+k);l(k)}})})();return{destroy:function(){h&&
h.destroy();h=null}}};g.create=function(a){return new g(a)};n.rpc_call=g});r.module("url_builder_casto",function(n){var i=function(c){console.assert(c.base_url);console.assert(c.cast_privhash);console.assert(c.cast_name);var b=c.base_url+"/"+c.cast_privhash+"/"+c.cast_name;if(c.mdata_srv_uri)b+="?mdata_srv_uri="+escape(c.mdata_srv_uri);return b};n.create=i;if(process.argv[1]==__filename){opts={base_url:null,cast_privhash:null,cast_name:null,mdata_srv_uri:null};n=function(c){c&&console.log(c+"\n");
console.log("usage: neoip-url-stream [-s url] base_url cast_privhash cast_name");console.log("");console.log("Build an url for neoip-casto");console.log("");console.log("-s|--mdata_srv_uri\n\t\tSet url for the mdata_srv.");console.log("-h|--help\tDisplay the inline help.")};for(var f=2;f<process.argv.length;f++){var g=process.argv[f],a=process.argv[f+1];if(g=="-s"||g=="--mdata_srv_uri"){opts.mdata_srv_uri=a;f+=1}else if(g=="-h"||g=="--help"){n();process.exit(0)}else break}if(process.argv.length-f<
3){n("missing parameters to buidl the url");process.exit(0)}opts.base_url=process.argv[f++];opts.cast_privhash=process.argv[f++];opts.cast_name=process.argv[f++];i=i(opts);console.log(i)}});r.module("url_builder_oload_t",function(n,i){var f=i("./collection").collection,g=i("./base64").base64,a=function(c){var b=new f,m=function(d){for(var h=0;;h++){var e="outter_var/dupuri/"+h;if(!b.has(e)){b.set(e,d);break}}},o=function(){try{if(!b.has("outter_uri"))throw Error("No outter_uri");if(!b.has("inner_uri"))throw Error("No inner_uri");
}catch(d){console.log("url_builder_oload_t not sane due to "+d);return false}return true},l=function(d){var h=g.decode_safe,e=d.substr(0,d.indexOf("/http:/"));for(d=d.substr(d.indexOf("/http:/")+1);;){var j=e.substr(e.lastIndexOf("/")+1);if(j.substr(0,1)=="*"){var k=j.match(/\*(.+)\*(.+)$/);j=k[1];k=k[2];j!="dupuri"?b.set("outter_var/"+j,k):m(h(k))}else if(j=="raw"||j=="flv")b.set("outter_var/mod",j);else break;e=e.substr(0,e.lastIndexOf("/"))}b.set("outter_uri",e);h=[];if(d.lastIndexOf("?")!=-1){var p=
d.substr(d.lastIndexOf("?")+1).split("&");for(e=0;e<p.length;e++){k=p[e].split("=");j=k[0];k=k[1];if(j.indexOf("neoip_metavar_")!=0)h.push(p[e]);else{j=j.substr(14);b.set("minner_var/"+j,k)}}d=d.substr(0,d.lastIndexOf("?"))}if(b.has("outter_var/subfile_level")){k=b.get("outter_var/subfile_level");j=null;for(e=0;e<k;e++)j=j?d.lastIndexOf("/",j-1):d.lastIndexOf("/");e=d.substr(j);b.set("outter_var/subfile_path",e);b.del("outter_var/subfile_level");d=d.substr(0,j)}d=d;if(h.length>0)d+="?"+h.join("&");
b.set("inner_uri",d)};c!==undefined&&l(c);return{outter_uri:function(d){b.set("outter_uri",d)},inner_uri:function(d){b.set("inner_uri",d)},outter_var:function(d,h){return b.set("outter_var/"+d,h)},minner_var:function(d,h){return b.set("minner_var/"+d,h)},dupuri:m,set:function(d,h){b.set(d,h);return this},get:b.get,get_dfl:b.get_dfl,del:b.del,has:b.has,is_sane:o,to_string:function(){var d=g.encode_safe,h="";console.assert(o());h+=b.get("outter_uri")+"/";if(b.has("outter_var/mod"))h+=b.get("outter_var/mod")+
"/";for(var e in b.get_dfl("outter_var",{}))if(e!="dupuri")if(e!="subfile_path")if(e!="mod"){h+="*"+e+"*";var j=b.get("outter_var/"+e);if(e=="http_peersrc_uri")j=url_encode_safe(j);h+=j;h+="/"}if(b.has("outter_var/subfile_path")){j=b.get("outter_var/subfile_path");j=j.split("/").length-1;h+="*subfile_level*"+j+"/"}for(var k in b.get_dfl("outter_var/dupuri",{})){h+="*dupuri*";h+=d(b.get("outter_var/dupuri/"+k));h+="/"}d=b.get("inner_uri");b.has("outter_var/subfile_path");j=b.get_dfl("outter_var/subfile_path",
null);k=d.indexOf("?");h+=k!=-1?d.substr(0,k):d;if(j)h+=j;if(k!=-1)h+=d.substr(k,d.length);for(e in b.get_dfl("minner_var",{})){h+=h.indexOf("?")==-1?"?":"&";h+="neoip_metavar_"+e+"="+escape(b.get("minner_var/"+e))}return h},from_string:l}};a.create=function(c){return new a(c)};n.url_builder_oload_t=a;n.create=a.create});r.module("webpeer",function(n,i){var f=i("./neoip_app_detect"),g=i("./url_builder_oload_t");webpeer_ready=function(a){f.webpack_probe(function(c){if(c=="toinstall")a(false);else if(c==
"toupgrade")a(true);else c=="installed"?a(true):console.assert(false)})};webpeer_avail=function(){return f.webpack_status()=="installed"};webpeer_url=function(a){if(!webpeer_avail())return a;return g.create(a).set("outter_uri",f.cache_get("oload").root_url).to_string()};n.ready=webpeer_ready;n.avail=webpeer_avail;n.url=webpeer_url});z.webpeer=r("./webpeer")})(window);
